joint3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_roll
    joint_speed: 1.0
    motor:
        id: 15
        init: 0
        min: 0
        max: 4095

joint4_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_pitch
    joint_speed: 1.0
    motor:
        id: 25
        init: 0
        min: 0
        max: 2047
